mutation CreateComment($articleId: ID!, $attributes: CommentAttributes!) {
  createComment(input: { articleId: $articleId, attributes: $attributes }) {
    comment {
      id
      body
      user {
        id
        name
        avatarUrl
      }
    }
    article {
      id
      commentsCount
    }
    errors {
      path
      message
    }
  }
}
