query Article($id: ID!) {
  article(id: $id) {
    id
    title
    body
    user {
      id
      name
    }
    comments {
      id
      body
      user {
        id
        name
        avatarUrl
      }
    }
    commentsCount
    favoritesCount
    favedByMe
  }
}
