mutation CreateAccount($attributes: AccountAttributes!) {
  createAccount(input: { attributes: $attributes }) {
    account {
      id
      name
    }
    errors {
      path
      message
    }
  }
}
