mutation CreateArticle($attributes: ArticleAttributes!) {
  createArticle(input: { attributes: $attributes }) {
    article {
      id
      title
      body
    },
    errors {
      path
      message
    }
  }
}
