mutation DestroyComment($id: ID!) {
  destroyComment(input: { id: $id }) {
    comment {
      id
    }
    article {
      id
      commentsCount
    }
    errors {
      path
      message
    }
  }
}
