query PagedArticles($page: Int, $pageSize: Int) {
  pagedArticles(page: $page, pageSize: $pageSize) {
    articles {
      id
      title
      user {
        id
        name
        avatarUrl
      }
      commentsCount
      likesCount
      createdAt
    }
    hasMore
  }
}
