query SearchArticles($keyword: String!) {
  searchArticles(keyword: $keyword) {
    id
    title
    user {
      id
      name
      avatarUrl
    }
    commentsCount
    favoritesCount
    createdAt
  }
}
