mutation UpdateArticle($id: ID!, $attributes: ArticleAttributes!) {
  updateArticle(input: { id: $id, attributes: $attributes }) {
    article {
      id
      title
      body
    },
    errors {
      path
      message
    }
  }
}
