mutation UpdateProfile($id: ID!, $attributes: ProfileAttributes!) {
  updateProfile(input: { id: $id, attributes: $attributes }) {
    profile {
      id
      name
      email
    }
    errors {
      path
      message
    }
  }
}
